services:
  - type: web
    name: pulsegen-frontend
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html